apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aceest
      env: blue
  template:
    metadata:
      labels:
        app: aceest
        env: blue
    spec:
      containers:
      - name: aceest
        image: kalyanimuppidi/aceest-fitness:local
        ports:
        - containerPort: 5000
