apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aceest
      env: green
  template:
    metadata:
      labels:
        app: aceest
        env: green
    spec:
      containers:
      - name: aceest
        image: kalyanimuppidi/aceest-fitness:v1.4
        ports:
        - containerPort: 5000
