apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-deployment
  labels:
    app: aceest
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aceest
      track: stable
  template:
    metadata:
      labels:
        app: aceest
        track: stable
    spec:
      containers:
      - name: aceest
        image: kalyanimuppidi/aceest-fitness:local
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /healthcheck/ready
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /healthcheck/live
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
