apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-a
  labels:
    app: aceest
    variant: a
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aceest
      variant: a
  template:
    metadata:
      labels:
        app: aceest
        variant: a
    spec:
      containers:
      - name: aceest
        # Variant A (example: v1.4)
        image: kalyanimuppidi/aceest-fitness:v1.4
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /healthcheck/ready
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
